version: "3.3"

services:
  postgres:
    container_name: bank_db
    image: postgres:14.2
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - bank-postgres:/var/lib/postgresql/data

  bank:
    container_name: bank-app
    command: "bundle exec rails server -p 3000 -b '0.0.0.0'"
    # entrypoint: ["tail", "-f", "/dev/null"]
    build:
      context: .
      dockerfile: ./Dockerfile.local
    volumes:
      - .:/bank
    links:
      - postgres
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
    stdin_open: true
    tty: true

volumes:
  bank-postgres:
