FROM ruby:2.7.6 AS bank-development

ENV BUNDLER_VERSION='2.3.7'

RUN apt-get update -qq && apt-get install -y vim\
        curl \
        build-essential \
        libpq-dev \
        postgresql-client \
        libsqlite3-dev \
        sqlite3

WORKDIR /bank

COPY . ./

RUN gem install bundler -v $BUNDLER_VERSION \
        && bundle config build.nokogiri --use-system-libraries \
        && bundle config set --local without 'production' \
        && bundle install